14810-datasets-names-in-ckan-are-misleading
konturio/geocint-mapaction pull request #108
Opened 2023-02-13 17:13 UTC by lgudyma-kontur

2023-02-14 16:03 UTC, Zkir requested changes

2023-02-14 16:03 UTC, Zkir commented on scripts/ma_dictionaries.py
> +    "bes": "Bonaire, (Sint Eustatius and Saba)",  # Country
In this case parentheses are not necessary. 
"Bonaire" is not a shorter name of a country.

2023-02-14 16:03 UTC, Zkir commented on scripts/ma_dictionaries.py
> +    "shn": "Saint Helena, (Ascension and Tristan da Cunha)",  # Country
Should be `Saint Helena, Ascension and Tristan da Cunha`

2023-02-14 16:04 UTC, Zkir commented
@lgudyma-kontur please change according to comments.

2023-02-15 09:45 UTC, Zkir approved these changes
looks ok

2023-02-15 09:46 UTC, merged

2023-02-17 10:56 UTC, amurKontur commented on scripts/ma_dictionaries.py
> +    "fsm": "Micronesia (Federated States of)",  # Country
I don't think that this fix is OK supported in future if other datasets are added. But as for now we can leave it as it is